#!/bin/bash -eu

maxseconds=180

. `dirname $0`/utils

usage 2 $# "DEST URL" "$@"

mkdir -p "$1"

# Stolen from https://gist.github.com/oneohthree/f528c7ae1e701ad990e6
slug=`echo "$2" | iconv -t ascii//TRANSLIT | sed -E 's/[^a-zA-Z0-9\.]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z`
slug="$1/$slug"
if [ -e $slug ]; then
  log "File $2 already downloaded, skipping"
else
  log2 "Downloading "$2" to $slug"
  set +e
  ffmpeg -loglevel 16 -nostdin -nostats -i "$2" -t $maxseconds -ac 1 -ab 128k "$slug"
  ok=$?
  set -e
  if [ $ok -eq 0 ]; then
    log "Done"
  else
    log "Error"
  fi
fi
