#!/bin/bash -eu

maxseconds=300

. utils

usage 2 $# "DEST URL" "$@"

mkdir -p "$1"

# Stolen from https://gist.github.com/oneohthree/f528c7ae1e701ad990e6
slug=`echo "$2" | iconv -t ascii//TRANSLIT | sed -E 's/[^a-zA-Z0-9\.]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z`
slug="$1/$slug"
if [ -e $slug ]; then
  log "File $1 already downloaded, skipping"
else
  log2 "Downloading "$2" to $slug"
  set +e
  ffmpeg -loglevel 16 -i "$2" -t $maxseconds -c:a copy "$slug"
  set -e
  log "Done"
fi
